# Generated by Django 4.2 on 2024-08-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua'), ('E', 'Eléctrico'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
