# Generated by Django 4.2 on 2024-08-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('F', 'Fuego'), ('P', 'Planta'), ('E', 'Eléctrico'), ('A', 'Agua'), ('T', 'Tierra')], max_length=30),
        ),
    ]
