# Generated by Django 4.2 on 2024-08-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('A', 'Agua'), ('L', 'Lagartija'), ('E', 'Eléctrico'), ('F', 'Fuego'), ('P', 'Planta')], max_length=30),
        ),
    ]
